import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Dict, Any, List
from dotenv import load_dotenv
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response, StreamingResponse
import io
from fpdf import FPDF

from predict import run_pipeline
from utils.carbon_engine import calculate_carbon_impact
from ml.data_fetcher import fetch_sentinel_data
import numpy as np

# Load environment variables
load_dotenv()

app = FastAPI(title="Sundarbans Sentinel API")

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production, specify the actual origin
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["Content-Disposition"],
)

class AnalysisRequest(BaseModel):
    geojson: Dict[str, Any]
    date_range: List[str]  # [start_date, end_date]

class ReportRequest(BaseModel):
    hectares_lost: float
    carbon_tons: float
    year: int
    coordinates: str

@app.get("/")
async def root():
    return {"message": "Welcome to Sundarbans Sentinel API"}

@app.post("/api/report")
async def generate_report(request: ReportRequest):
    """
    Generates a professional PDF environmental impact report.
    """
    try:
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", "B", 16)
        pdf.set_text_color(16, 185, 129) # Emerald-500
        pdf.cell(0, 10, "Sundarbans Sentinel: Environmental Impact Report", ln=True, align="C")
        pdf.ln(10)
        
        # Metadata
        pdf.set_font("Arial", "", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, f"Analysis Year: {request.year}", ln=True)
        pdf.cell(0, 5, f"Location: {request.coordinates}", ln=True)
        pdf.cell(0, 5, f"Report Generated: {request.year}-05-03", ln=True)
        pdf.ln(10)
        
        # Impact Summary Table
        pdf.set_font("Arial", "B", 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "Impact Summary", ln=True)
        
        pdf.set_font("Arial", "B", 12)
        pdf.cell(95, 10, "Metric", border=1)
        pdf.cell(95, 10, "Value", border=1, ln=True)
        
        pdf.set_font("Arial", "", 12)
        pdf.cell(95, 10, "Total Mangrove Loss", border=1)
        pdf.cell(95, 10, f"{request.hectares_lost} Hectares", border=1, ln=True)
        pdf.cell(95, 10, "Total Carbon Emitted", border=1)
        pdf.cell(95, 10, f"{request.carbon_tons} Tons", border=1, ln=True)
        pdf.ln(15)
        
        # Social Impact Assessment
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Social Impact Assessment", ln=True)
        pdf.set_font("Arial", "", 11)
        impact_text = (
            "The observed mangrove loss directly threatens local livelihoods. "
            "Mangroves serve as a natural buffer against cyclones and storm surges. "
            "Their degradation increases the vulnerability of coastal villages, "
            "potentially leading to forced displacement and loss of traditional fishing grounds."
        )
        pdf.multi_cell(0, 7, impact_text)
        
        # Footer
        pdf.set_y(-30)
        pdf.set_font("Arial", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "This report is generated by Sundarbans Sentinel Monitoring System.", align="C")

        # Output to buffer
        pdf_output = io.BytesIO()
        pdf_str = pdf.output()
        if isinstance(pdf_str, bytearray):
            pdf_output.write(pdf_str)
        else:
            pdf_output.write(pdf_str.encode('latin1') if isinstance(pdf_str, str) else pdf_str)
            
        pdf_output.seek(0)
        
        headers = {
            'Content-Disposition': f'attachment; filename="Sundarbans_Impact_Report_{request.year}.pdf"'
        }
        
        return StreamingResponse(pdf_output, media_type="application/pdf", headers=headers)
        
    except Exception as e:
        print(f"Report generation error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to generate report: {str(e)}")

@app.get("/api/tiles/{year}/{z}/{x}/{y}.png")
async def get_tiles(year: int, z: int, x: int, y: int):
    """
    Endpoint to serve dynamic satellite tiles for a specific year.
    Ensures that imagery is dynamic and responds to the selected year.
    """
    print(f"DEBUG: Generating tiles for year: {year} at zoom {z}, x {x}, y {y}")
    # In production, this would call a custom tile server or data provider
    # Ensure the year is passed correctly to any underlying fetcher
    return Response(content=b"", media_type="image/png")

@app.get("/api/stats")
async def get_stats(year: int):
    """
    Returns annual summary statistics for the selected year.
    """
    # Simulate dynamic stats based on year
    # In production, these would be pulled from a database of analyzed results
    np.random.seed(year)
    stats = {
        "year": year,
        "carbon_loss": 2000 + (year - 2022) * 150 + np.random.randint(0, 100),
        "erosion_rate": 150 + (year - 2022) * 5 + np.random.uniform(0, 5),
        "vulnerability_index": 0.65 + (year - 2022) * 0.02
    }
    return stats

@app.post("/analyze")
async def analyze_area(request: AnalysisRequest):
    if not request.geojson or len(request.date_range) != 2:
        raise HTTPException(status_code=400, detail="Invalid GeoJSON or date range")
    
    # Extract year from date_range for dynamic filtering
    year = int(request.date_range[0].split("-")[0])
    print(f"Analyzing area for year: {year}")
    
    try:
        # 1. Fetch dynamic satellite data for the selected year (Sentinel-2 L2A)
        cube_data = fetch_sentinel_data(request.geojson, year)
        
        # 2. Run AI change detection (Siamese UNET)
        # predict.py's preprocess_cube extracts T1 (previous year) and T2 (selected year)
        change_mask = run_pipeline(cube_data)
        
        # 3. Calculate NDVI for carbon engine
        # Assuming cube_data channels: 0=Red, 1=Green, 2=Blue, 3=NIR
        # Using T2 (latest imagery) for NDVI
        t2_data = cube_data[-1]
        red = t2_data[0].astype(float)
        nir = t2_data[3].astype(float)
        ndvi = (nir - red) / (nir + red + 1e-8)
        
        # 4. Calculate carbon impact
        carbon_results = calculate_carbon_impact(change_mask, ndvi)
        
        return {
            "status": "success", 
            "message": f"Analysis completed for year {year}",
            "analysis_results": {
                "eroded_pixels": float(np.sum(change_mask)),
                "hectares_lost": carbon_results["hectares_lost"],
                "total_carbon_emitted": carbon_results["total_carbon_emitted"],
                "mask_shape": list(change_mask.shape)
            }
        }
    except Exception as e:
        print(f"Error during analysis: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
