import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Dict, Any, List
from dotenv import load_dotenv
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response, StreamingResponse
import io
from fpdf import FPDF
import ee
import json

from predict import run_pipeline
from utils.carbon_engine import calculate_carbon_impact
from ml.data_fetcher import fetch_sentinel_data
import numpy as np

# Load environment variables
load_dotenv()

# Google Earth Engine Authentication
GEE_JSON_PATH = os.path.join(os.path.dirname(__file__), "gee-service-account.json.json")

# Global GEE initialization status
GEE_INITIALIZED = False

def initialize_gee():
    global GEE_INITIALIZED
    if not os.path.exists(GEE_JSON_PATH):
        print(f"CRITICAL: GEE Service Account file missing at {GEE_JSON_PATH}")
        GEE_INITIALIZED = False
        return False
    
    try:
        with open(GEE_JSON_PATH) as f:
            account_info = json.load(f)
            client_email = account_info.get("client_email")
            
        if not client_email:
            print("CRITICAL: Invalid Service Account JSON - missing client_email")
            GEE_INITIALIZED = False
            return False
            
        credentials = ee.ServiceAccountCredentials(client_email, GEE_JSON_PATH)
        ee.Initialize(credentials)
        print("Google Earth Engine initialized successfully.")
        GEE_INITIALIZED = True
        return True
    except Exception as e:
        print(f"CRITICAL: GEE Initialization Failed: {str(e)}")
        if "permission" in str(e).lower():
            print("ERROR: Service Account may lack necessary Earth Engine permissions.")
        GEE_INITIALIZED = False
        return False

# Initialize GEE on startup
initialize_gee()

app = FastAPI(title="Sundarbans Sentinel API")

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["Content-Disposition"],
)

class AnalysisRequest(BaseModel):
    geojson: Dict[str, Any]
    date_range: List[str]  # [start_date, end_date]

class ReportRequest(BaseModel):
    hectares_lost: float
    carbon_tons: float
    year: int
    coordinates: str

@app.get("/")
async def root():
    return {"message": "Welcome to Sundarbans Sentinel API"}

@app.post("/api/report")
async def generate_report(request: ReportRequest):
    """
    Generates a professional PDF environmental impact report.
    """
    try:
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", "B", 16)
        pdf.set_text_color(16, 185, 129) # Emerald-500
        pdf.cell(0, 10, "Sundarbans Sentinel: Environmental Impact Report", ln=True, align="C")
        pdf.ln(10)
        
        # Metadata
        pdf.set_font("Arial", "", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, f"Analysis Year: {request.year}", ln=True)
        pdf.cell(0, 5, f"Location: {request.coordinates}", ln=True)
        pdf.cell(0, 5, f"Report Generated: {request.year}-05-03", ln=True)
        pdf.ln(10)
        
        # Impact Summary Table
        pdf.set_font("Arial", "B", 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "Impact Summary", ln=True)
        
        pdf.set_font("Arial", "B", 12)
        pdf.cell(95, 10, "Metric", border=1)
        pdf.cell(95, 10, "Value", border=1, ln=True)
        
        pdf.set_font("Arial", "", 12)
        pdf.cell(95, 10, "Total Mangrove Loss", border=1)
        pdf.cell(95, 10, f"{request.hectares_lost} Hectares", border=1, ln=True)
        pdf.cell(95, 10, "Total Carbon Emitted", border=1)
        pdf.cell(95, 10, f"{request.carbon_tons} Tons", border=1, ln=True)
        pdf.ln(15)
        
        # Social Impact Assessment
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Social Impact Assessment", ln=True)
        pdf.set_font("Arial", "", 11)
        impact_text = (
            "The observed mangrove loss directly threatens local livelihoods. "
            "Mangroves serve as a natural buffer against cyclones and storm surges. "
            "Their degradation increases the vulnerability of coastal villages, "
            "potentially leading to forced displacement and loss of traditional fishing grounds."
        )
        pdf.multi_cell(0, 7, impact_text)
        
        # Footer
        pdf.set_y(-30)
        pdf.set_font("Arial", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "This report is generated by Sundarbans Sentinel Monitoring System.", align="C")

        # Output to buffer
        pdf_output = io.BytesIO()
        pdf_str = pdf.output()
        if isinstance(pdf_str, bytearray):
            pdf_output.write(pdf_str)
        else:
            pdf_output.write(pdf_str.encode('latin1') if isinstance(pdf_str, str) else pdf_str)
            
        pdf_output.seek(0)
        
        headers = {
            'Content-Disposition': f'attachment; filename="Sundarbans_Impact_Report_{request.year}.pdf"'
        }
        
        return StreamingResponse(pdf_output, media_type="application/pdf", headers=headers)
        
    except Exception as e:
        print(f"Report generation error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to generate report: {str(e)}")

@app.get("/api/tiles")
async def get_tiles(year: int, mode: str = "natural"):
    """
    Returns a dynamic Google Earth Engine MapID URL for satellite tiles.
    Accepts year and mode (natural/ndvi) as query parameters.
    """
    if not GEE_INITIALIZED:
        raise HTTPException(status_code=503, detail="Google Earth Engine not initialized. Check server logs.")
    
    print(f"DEBUG: Backend received year request for: {year}, mode: {mode}")
    try:
        # Sundarbans bounding box (specific and compact to avoid timeouts)
        region = ee.Geometry.Rectangle([88.5, 21.5, 89.2, 22.2])
        
        start_date = f"{year}-01-01"
        end_date = f"{year}-12-31"
        
        # Filter Sentinel-2 L2A collection using the dynamic year
        collection = (ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
                      .filterBounds(region)
                      .filterDate(start_date, end_date)
                      .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20)))
        
        # Check if collection is empty
        count = collection.size().getInfo()
        print(f"DEBUG: Found {count} images for year {year}")
        
        if count == 0:
            # Fallback to a wider date range if no images found in the specific year
            print(f"WARNING: No images found for {year}, expanding search...")
            collection = (ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
                          .filterBounds(region)
                          .filterDate(f"{year-1}-01-01", f"{year+1}-12-31")
                          .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 30)))

        # Create cloud-free composite using median reducer
        image = collection.median().clip(region)
        
        if mode == "ndvi":
            ndvi = image.normalizedDifference(['B8', 'B4']).rename('NDVI')
            vis_params = {
                'min': 0,
                'max': 0.8,
                'palette': ['#FFFFFF', '#CE7E45', '#DF923D', '#F1B555', '#FCD163', '#99B718', '#74A901', '#66A000', '#529400', '#3E8601', '#207401', '#056201', '#004C00', '#023B01', '#012E01', '#011D01', '#011301']
            }
            map_id_dict = ndvi.getMapId(vis_params)
        else:
            # Natural Color (B4, B3, B2)
            vis_params = {
                'bands': ['B4', 'B3', 'B2'],
                'min': 0,
                'max': 3000,
                'gamma': 1.4
            }
            map_id_dict = image.getMapId(vis_params)
            
        return {"url": map_id_dict['tile_fetcher'].url_format}
        
    except Exception as e:
        print(f"GEE Tile Generation Error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"GEE Tile Error: {str(e)}")

@app.get("/api/stats")
async def get_stats(year: int):
    """
    Returns annual summary statistics for the selected year.
    """
    # Simulate dynamic stats based on year
    # In production, these would be pulled from a database of analyzed results
    np.random.seed(year)
    stats = {
        "year": year,
        "carbon_loss": 2000 + (year - 2022) * 150 + np.random.randint(0, 100),
        "erosion_rate": 150 + (year - 2022) * 5 + np.random.uniform(0, 5),
        "vulnerability_index": 0.65 + (year - 2022) * 0.02
    }
    return stats

@app.post("/api/analyze")
async def analyze_area(request: AnalysisRequest):
    if not GEE_INITIALIZED:
        raise HTTPException(status_code=503, detail="Google Earth Engine not initialized. Check server logs.")
        
    if not request.geojson or len(request.date_range) != 2:
        raise HTTPException(status_code=400, detail="Invalid GeoJSON or date range")
    
    # Extract year from date_range for dynamic filtering
    year = int(request.date_range[0].split("-")[0])
    print(f"Analyzing area for year: {year}")
    
    try:
        # 1. Fetch dynamic satellite data for the selected year (Sentinel-2 L2A)
        cube_data = fetch_sentinel_data(request.geojson, year)
        
        # 2. Run AI change detection (Siamese UNET)
        # predict.py's preprocess_cube extracts T1 (previous year) and T2 (selected year)
        change_mask = run_pipeline(cube_data)
        
        # 3. Calculate NDVI for carbon engine
        # Assuming cube_data channels: 0=Red, 1=Green, 2=Blue, 3=NIR
        # Using T2 (latest imagery) for NDVI
        t2_data = cube_data[-1]
        red = t2_data[0].astype(float)
        nir = t2_data[3].astype(float)
        ndvi = (nir - red) / (nir + red + 1e-8)
        
        # 4. Calculate carbon impact
        carbon_results = calculate_carbon_impact(change_mask, ndvi)
        
        return {
            "status": "success", 
            "message": f"Analysis completed for year {year}",
            "analysis_results": {
                "eroded_pixels": float(np.sum(change_mask)),
                "hectares_lost": carbon_results["hectares_lost"],
                "total_carbon_emitted": carbon_results["total_carbon_emitted"],
                "mask_shape": list(change_mask.shape)
            }
        }
    except Exception as e:
        print(f"Error during analysis: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
